import KeystoreUtils from "./keystoreUtils.js";
import path from "path";    
import dotenv from "dotenv";
import {Wallet} from "@ethersproject/wallet";
import {readFileSync, writeFileSync} from "fs";

dotenv.config();


async function keyStoreDemo() {

    try{
        //1. get private key from env
        const privateKey = process.env.PRIVATE_KEY;
        if(!privateKey){
            throw new Error("PRIVATE_KEY is not set in environment varibales");
        }


        //2. set password and file path
        console.log("Starting KeyStore demo...");
        const password = process.env.KEYSTORE_PASSWORD;
        const keystoreFilePath = path.join(process.cwd(), '.key', 'keystore.json');


        //3. encrypt private key to get keystore
        console.log("Encrypting private key to generate keystore...");
        const keystore = await KeystoreUtils.encryptPrivateKey(privateKey, password);
        console.log("KeyStre generated:", keystore);

        //4.save key store to file
        await KeystoreUtils.saveKeystore(keystore, keystoreFilePath);
        console.log("Keystore saved to file:", keystoreFilePath);

        //5. read key store from file
        console.log("\n start to read keystore from file...");
        const readKeystore = await KeystoreUtils.loadKeystore(keystoreFilePath);
        console.log("Keystore read from file:", readKeystore);
        
        //6. decrypt private key from keystore
        console.log("Decrypting privae key from keystore...");
        const decryptePrivateKey = await KeystoreUtils.decryptPrivateKey(readKeystore, password);
        console.log("Decrypted private key:", decryptePrivateKey);

        //7.verify
        if(decryptePrivateKey.toLowerCase() === privateKey.toLowerCase()){
            console.log("Success: Decrypted private key matches the original private key.");
        }else{
            console.error("Error: Decrypted private key does not match the original private key.");
        }


    }catch(error){
        console.error("Key store demo failed:", error);
    }
}


async function encryptByWallet() {
    try{
        //1. get private key from env
        const privateKey = process.env.PRIVATE_KEY;
        if(!privateKey){
            throw new Error("PRIVATE_KEY is not set in environment varibales");
        }


        //2. set password and file path
        console.log("Starting KeyStore demo...");
        const password = process.env.KEYSTORE_PASSWORD;
        const keystoreFilePath = path.join(process.cwd(), '.key', 'keystore.json');
        console.log("password:", password);

        //3. encrypt private key to get keystore
        console.log("Encrypting private key to generate keystore using ethers Wallet...");
        const wallet = new Wallet(privateKey);
        const keystoreJson = await wallet.encrypt(password);
        console.log("KeyStre generated by Wallet:", keystoreJson);

        //4.save key store to file
        writeFileSync(keystoreFilePath, keystoreJson, 'utf-8');
        console.log("Keystore saved to file:", keystoreFilePath);


        //read keystore from file
        const keystoreContent = readFileSync(keystoreFilePath, 'utf-8');
        const keystore = JSON.parse(keystoreContent);
        console.log("Keystore content read successfully.");

        //3. decrypt keystore to get private key
        const wallet1 = await Wallet.fromEncryptedJson(JSON.stringify(keystore), password);
        const privateKey1 = wallet1.privateKey;
        console.log("Decrypted private key:", privateKey);

        //4.verify
        if(privateKey1.toLowerCase() === privateKey.toLowerCase()){
            console.log("Success: Decrypted private key matches the original private key.");
        }else{
            console.error("Error: Decrypted private key does not match the original private key.");
        }

    }catch(error){
        console.error("Encrypt by wallet failed:", error);
    }
}
//keyStoreDemo();
encryptByWallet();
